# Generated by Django 3.1 on 2020-08-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeraccount',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
